### PR TITLE
Fixes #7

### LINKED ISSUE #7: Feature suggestion: /train [username]
I will be working on this.

http://chicken-craft.boards.net/thread/347/tips-admin?page=1&scrollTo=2180

### PR DESCRIPTION
**Pull request by DUFCLiam**
This is a few changes.

Resolves #7

### CODE REVIEW

**Comment by DUFCLiam** [comment]
Fixes #7

**Comment by AvalancheYT** [comment]
No thanks, and in command personal, there is no delete, it's just /loginmsg set null

**Comment by DUFCLiam** [comment]
@AvalancheYT, I was going to make "delete" set the message to null.

**Comment by AvalancheYT** [comment]
@DUFCLiam, It is already added to my mod, will update to the server and github soon.

**Pull request closed without merging**
